//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjP2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Curso
    {
        public int Id_aluno { get; set; }
        public string NOME { get; set; }
        public string CPF { get; set; }
        public Nullable<int> EMEC_CURSO { get; set; }
        public string CURSO1 { get; set; }
        public Nullable<int> ANO_INGRESSO { get; set; }
        public string SEMESTRE_INGRESSO { get; set; }
        public string DATA_EXPEDICAO_DIPLOMA { get; set; }
        public string DATA_REGISTRO_DIPLOMA { get; set; }
        public Nullable<int> NUMERO_REGISTRO_DIPLOMA { get; set; }
        public string DATA_PUBLICACAO_DOU { get; set; }
        public Nullable<int> EMEC_IES_EXPEDIDORA { get; set; }
        public Nullable<int> EMEC_IES_REGISTRADORA { get; set; }
    }
}
